// Define an interface for your data
export interface ICashTrans {
  ID: string;
  EntryDate: Date;
  EnteredBy: string;
  TransDate: Date;
  CarReg: string;
  Driver: string;
  DriverDay: string;
  CashinObligation: number;
  CashReceived: number;
  BonusReceived: number;
  DriverLoan: number;
  DriverLoanNote: string;
  CashinDeficit: number;
  CashinNote: string;
  OwnerShare: number;
  OwnerShareNote: string;
  OwnerPayout: number;
  OwnerPayoutNote: string;
  OwnerPayoutPOP: string;
  OwnerLoan: number;
  OwnerLoanNote: string;
  OwnerLoanPOP: string;
  OwnerPendingPayout: number;
  CompanyShare: number;
  CompanyPayout: number;
  CompanyPayoutNote: string;
  CompanyPayoutPOP: string;
  CompanyExpenses: number;
  CompanyExpensesNote: string;
  CompanyExpensesPOP: string;
  CarOwnerNRC: string;
  FundsStatus: string;
  Margin: number;
  TotalLoans: number;
  TotalCashin: number;
  PendingPayout: number;
  TotalPayout: number;
  TotalCashinObligation: number;
  CollectionRate: number;
  TotalPaidOut: number;
  CompanyPendingPayout: number;
}

import mongoose from 'mongoose';
const CashTransSchema = new mongoose.Schema({
  ID: String,
  EntryDate: Date,
  EnteredBy: String,
  TransDate: Date,
  CarReg: String,
  Driver: String,
  DriverDay: String,
  CashinObligation: Number,
  CashReceived: Number,
  BonusReceived: Number,
  DriverLoan: Number,
  DriverLoanNote: String,
  CashinDeficit: Number,
  CashinNote: String,
  OwnerShare: Number,
  OwnerShareNote: String,
  OwnerPayout: Number,
  OwnerPayoutNote: String,
  OwnerPayoutPOP: String,
  OwnerLoan: Number,
  OwnerLoanNote: String,
  OwnerLoanPOP: String,
  OwnerPendingPayout: Number,
  CompanyShare: Number,
  CompanyPayout: Number,
  CompanyPayoutNote: String,
  CompanyPayoutPOP: String,
  CompanyExpenses: Number,
  CompanyExpensesNote: String,
  CompanyExpensesPOP: String,
  CarOwnerNRC: String,
  FundsStatus: String,
  Margin: Number,
  TotalLoans: Number,
  TotalCashin: Number,
  PendingPayout: Number,
  TotalPayout: Number,
  TotalCashinObligation: Number,
  CollectionRate: Number,
  TotalPaidOut: Number,
  CompanyPendingPayout: Number,
});
