export type AssertInfo = {
  ID: number;
  EnteredBy: string;
  EntryDate: Date;
  Status: 'Active' | 'Inactive';
  CarOwnerNRC: string;
  Cashintype: string | null;
  AssertRegNumber: string | null;
  AssertMake: string | null;
  AssertModel: string | null;
  ChassisNumber: string | null;
  EngineNumber: string | null;
  Colour: string | null;
  YearMake: string | null;
  RoadTaxExpiry: Date | null;
  FitnessExpiry: Date | null;
  InsuranceType: string | null;
  InsuranceName: string | null;
  InsuranceExpiry: Date | null;
  NextPayDate: Date | null;
  ProjectedPay: number | null;
  NextServiceDate: Date | null;
  NextCarCheck: Date | null;
  WhiteBookDoc: string | null;
  InsuranceDoc: string | null;
  ContractDoc: string | null;
  CarOwnerName: string | null;
  DetailVehicleInfo: string | null;
  FullVehInfo: string | null;
  VehicleInfo: string | null;
};
